name: Collecting tweets and render table
on:
  push

jobs:
  collect:
    name: Collect tweets
    runs-on: ubuntu-latest
    container: rocker/tidyverse
    
    env:
      TW_API_KEY: ${{ secrets.TW_API_KEY }}
      TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}
      TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
      TW_SECRET_TOKEN: ${{ secrets.TW_SECRET_TOKEN }}
      SHEET_PATH: ${{ secrets.SHEET_PATH }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run collecting script
        run: |-
          Rscript R/collecting_likes.R
          
      - name: Save result as artifact
        uses: actions/upload-artifact@v1
        with:
          name: tw_table
          path: tw_fav.csv

