name: Collecting tweets and render table
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'
    - cron: '0 12 * * 4'

jobs:
  collect:
    name: Collect tweets and render
    runs-on: ubuntu-latest
    container: rocker/verse
    
    env:
      TW_API_KEY: ${{ secrets.TW_API_KEY }}
      TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}
      TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
      TW_SECRET_TOKEN: ${{ secrets.TW_SECRET_TOKEN }}
      SHEET_PATH: ${{ secrets.SHEET_PATH }}
      GOOGLE_MAIL: ${{ secrets.GOOGLE_MAIL }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Decrypt large secret
        run: ./secret/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Install dependencies
        run: |
          remotes::install_cran("rtweet")
          remotes::install_cran("googlesheets4")
          remotes::install_cran("reactable")
          remotes::install_github("ropenscilabs/icon")
        shell: Rscript {0}

      - name: Run collecting script
        run: |-
          Rscript R/collecting_likes.R
          
      - name: Save result as artifact
        uses: actions/upload-artifact@v1
        with:
          name: tw_table
          path: tw_fav.csv
          
      - name: Render table
        run: |-
          rmarkdown::render("Rmd/tw_table.Rmd", output_file = "index.html", output_dir = ".")
        shell: Rscript {0}
      
      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir .  
